export const GET_SINGLE_POST = 'GET_SINGLE_POST';
export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST';
export const ADD_POST = 'ADD_POST';
// export const REMOVE_POST = 'REMOVE_POST';
export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS';
export const GET_SINGLE_POST_SUCCESS = 'GET_SINGLE_POST_SUCCESS';
export const GET_POST_FAILURE = 'GET_POST_FAILURE';

//TODO: use enum